baseurl: '/'
permalink: pretty
title: 'Connect Lappin'

logo:
  mobile: "images/logo/logo-mobile.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"

collections:
 updates:
   output: true

defaults:
 - scope:
     path: ""
     type: "updates"
   values:
     layout: "updates"

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
