name: deploy-preview
run-name: ${{ github.actor }} deployed a preview page
on: 
  pull_request:
    # Sequence of patterns matched against refs/heads
      branches:
        - main
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1.0.12
      - name: Deploy PR Preview
        # You may pin to the exact commit or the version.
        # uses: rossjrw/pr-preview-action@f31d5aa7b364955ea86228b9dcd346dc3f29c408
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          preview_branch: main

